### ISSUE TITLE
idnum2itemdesctable does not work properly

### ISSUE THREAD

**Issue by bgamez23** [zackdreaver/ROenglishPRE#1] opened 2016-01-03 02:08 UTC
the item description is not working properly there is no item description using 2012-04-10 client

**Comment by zackdreaver** [comment] 2016-01-03 04:10
If you're diffing your client with "Read Data folder first" with NEMO patcher
then test it by putting your txt files in "data", it won't work properly.
You should put in GRF file.
It's an issue with the differ tool (NEMO)

**Comment by bgamez23** [comment] 2016-01-03 04:51
The old version of it works fine.but when i use the latest version item description does not show.

**Comment by bgamez23** [comment] 2016-01-03 04:53
I got the same issue with thishttps://github.com/ROClientSide/Translation/issues/49#issuecomment-168462151

**Comment by zackdreaver** [comment] 2016-01-03 05:12
which project  do you use?
this project or another one?
both has different files

**Comment by bgamez23** [comment] 2016-01-03 05:28
I just try both.but only the older version only works fine.

**Comment by zackdreaver** [comment] 2016-01-04 09:54
Ok, I've made some test with 2012-04-10aRagexeRE and 2008-03-25Sakexe
But I'am unable to reproduce your issue,
I believe it's a client exe issue not a translated files issue.

**Comment by bgamez23** [comment] 2016-01-04 10:53
RagexeRE will not work.try to use Ragexe only.

**Comment by zackdreaver** [comment] 2016-01-04 12:01
Server side only support RagexeRE of 2012-04-10, and i don't have Ragexe to test

**Comment by bgamez23** [comment] 2016-01-04 12:30
I dont think so.what emulator are you using?i use both rA and herc and everything worls fine for me for 2012-04-10aRagexe.and also cash shop works fine without any issue.only the item description is not working fine so it is not related on any emulator

**Comment by zackdreaver** [comment] 2016-01-04 13:35
Both, but i don't have Ragexe to test.
hmm.. I have no idea what the cause of your issue as i can't reproduce it.
Maybe you can give me a clue what things that you add to client.

**Comment by bgamez23** [comment] 2016-01-04 16:10
me too i still have no idea why this thing is not working properly. but if i use the old itemdesc the item description works fine.

**Comment by bgamez23** [comment] 2016-01-04 16:31
http://s9.postimg.org/6llhjr9xr/image.jpg
http://s13.postimg.org/s93vcgqcn/image.jpg

http://s16.postimg.org/i5wk311b9/screen_Milag_RO000.jpg

**Comment by zackdreaver** [comment] 2016-01-04 18:13
Hmm i suspect that your client read num2itemdesctable.txt instead idnum2itemdesctable.txt
for identified items because I delete many desc inside num2itemdesctable.txt, can you check other items like armor, weapon etc ?

**Comment by bgamez23** [comment] 2016-01-05 02:05
the problem only occurred when i change the idnum2itemdesctable not the num2itemdesctable.

**Comment by bgamez23** [comment] 2016-01-05 12:00
the other repository already solve this issue.
https://github.com/ROClientSide/Translation/issues/49#issuecomment-168965811

**Comment by zackdreaver** [comment] 2018-03-13 11:16
Because of no feedback for years, I'll now close this issue.
Feel free to open new issue if issue still presents with current files.

**Closed as completed by zackdreaver** 2018-03-13 11:16 UTC
