### ISSUE TITLE
Many items have the wrong resource name?

### ISSUE THREAD

**Issue by distilled1** [zackdreaver/ROenglishPRE#3] opened 2016-07-07 03:06 UTC
Hi, I'm not sure if this is correct, but it seems like there are many items with the wrong "identifiedResourceName" in this translation project such as CD in mouth "ÀÔ¿¡¹«´ÂÄÞÆÑÆ®µð½ºÅ©" or Stunner Shades "ºí¶óÀÎµå¾È°æ".
These resource names don't show up in any data.grf I've ever loaded into a grf editor, whether it's data from 2012, or updated data from 2016.
When in game, it gives a resource error and cannot find the corresponding data for certain items.

**Comment by zackdreaver** [comment] 2016-07-07 03:59
Hello,
I'm unable to reproduce your issue,
like the other open issue that have no feedback until now.
I believe its because of localization issue with your PC which is unable to read the fonts inside grf/lua.
If you unable to find the files inside kRO's data.grf, you can add this https://github.com/zackdreaver/RO-Clientresources

These are mine, no issue so far:
Cd in Mouth
https://s31.postimg.org/5n0rpwm4r/cdim.jpg

Stunner Glasses
https://s32.postimg.org/5afe7fad1/stunner.jpg

Can I see your screen shot of the itemInfo files?

**Comment by zackdreaver** [comment] 2018-03-13 11:13
Because of no feedback for years, I'll now close this issue.
Feel free to open new issue if issue still presents with current files

**Closed as completed by zackdreaver** 2018-03-13 11:13 UTC
